AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for awscli-on-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  AwscliLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./awscli-lambda
      DockerTag: python3.8-v1

Outputs:
  AwscliLambdaFunction:
    Description: "awscli-lambda Function ARN"
    Value: !GetAtt AwscliLambdaFunction.Arn
  AwscliLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for awscli-lambda function"
    Value: !GetAtt AwscliLambdaFunctionRole.Arn
